FROM node:20-alpine

WORKDIR /app

COPY frontend/package.json frontend/package-lock.json* ./
RUN npm install

COPY frontend/public ./public
COPY frontend/src ./src
COPY frontend/tsconfig.json ./tsconfig.json

CMD ["npm", "run", "build"]
